### ISSUE TITLE
Design a logo

### ISSUE THREAD

**Issue by qw-erty** [qw-erty/myTree#10]
design a logo and add it to the tittle bar,
make sure the logo matches with the theme

**Comment by dazzlerkumar** [comment]
Assign this to me.

**Comment by qw-erty** [comment]
@dazzlerkumar go ahead

**Comment by dazzlerkumar** [comment]
@qw-erty , Will you suggest any color palette?

**Comment by qw-erty** [comment]
Great Logo was added @dazzlerkumar
