### ISSUE TITLE
make a navbar

### ISSUE THREAD

**Issue by qw-erty** [qw-erty/myTree#12]
navbar shoud have the following sections 
=> right side: home ,contact us, about us
=> left side: tittle { MY TREE}

**Comment by a-rokay** [comment]
I can work on this

**Comment by qw-erty** [comment]
@a-rokay go ahead

**Comment by a-rokay** [comment]
![image](https://user-images.githubusercontent.com/86167097/135720051-4c8040b0-d57f-439e-97e5-ba80e60e58c9.png)

How's this?

**Comment by qw-erty** [comment]
nice , I think there were some other push on the repo , fetch then and then create pull request
