### ISSUE TITLE
Add  Footer

### ISSUE THREAD

**Issue by qw-erty** [qw-erty/myTree#13]
The content inthe footer can be of your choice but keep is short ,

you can also put following content in footer: "Made with ❤ "

**Comment by nisha331** [comment]
can I work on this?

**Comment by qw-erty** [comment]
go on @nisha331

**Comment by hrushikeshrout** [comment]
Hey! I would like to work on this. Can you assign this to me?

**Comment by garimavs** [comment]
Hello! I want to add more features to the present footer section. Would you mind assigning it to me?

**Comment by qw-erty** [comment]
go ahead @garimavs

**Comment by qw-erty** [comment]
Any further suggestion in footer are welcomed
