### ISSUE TITLE
Create Basic About Us page

### ISSUE THREAD

**Issue by qw-erty** [qw-erty/myTree#23]
Create a basic About Us Page 

give it a tittle of About US 
then add a section on importance of trees then you may add your views on importance of the trees in our nature

**Comment by Zackaria-Slimane** [comment]
Heyo,
would like to work on this page ! lemme know if i have your permission to do so 😃

**Comment by Rishi22-Coding** [comment]
hey @qw-erty let me know how is it

**Comment by Debdeep1** [comment]
Hey! I would like to work on this! Do let me know if you want to permit me to work on this!

**Comment by Radhey100** [comment]
Please assign.me I will do

**Comment by swaraj-ssk** [comment]
I have earlier done work in building websites, can you assign me this project ?

**Comment by aachalmodak** [comment]
I am interested in this issue, please assign me this!!

**Comment by hrushikeshrout** [comment]
Hey! I would like to work on this. Can you assign this to me?

**Comment by qw-erty** [comment]
A basic about Us page is added
