### ISSUE TITLE
create A good Home Page

### ISSUE THREAD

**Issue by qw-erty** [qw-erty/myTree#41]
Make a good home page for the website , the homepage should be Good looking and you can add your creativity

**Comment by JanviRaina** [comment]
Hey! I would like to work on this.Can you assign this to me.

**Comment by qw-erty** [comment]
go ahead @JanviRaina

**Comment by LunlunChin** [comment]
Hi!, can I help on this too?

**Comment by Madhavman** [comment]
i will do

**Comment by qw-erty** [comment]
a home page is created by @JanviRaina .
@LunlunChin and @Madhavman you may suggest any improvements in that and start working by opening issue.
